#
#  Copyright (c) 2000, 2026, Oracle and/or its affiliates.
#
#  Licensed under the Universal Permissive License v 1.0 as shown at
#  https://oss.oracle.com/licenses/upl.
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
#                                                                             #
# These properties override the default properties in build-import.xml.       #
#                                                                             #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #

ivy.artifactory.server.public=http://tangosol-build.us.oracle.com:8081/artifactory
ivy.path.public=virtual-release
ivy.path.internal=internal-snapshot
ivy.file=ivy-snapshot.xml
build.groupId_maven=com.oracle.coherence
build.version_maven=14.1.2-0-8-SNAPSHOT
